<a href="https://colab.research.google.com/github/CharlesRMcCullough/PyTorch-Udemy/blob/main/ManipulatingTensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

## Manipulating Tensors

### Tensor operations include:
* Addition
* Subtraction
* Multiplication
* Division
* Matrix multiplaction

In [ ]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
tensor * 10

tensor([10, 20, 30])

In [ ]:
tensor - 10

tensor([-9, -8, -7])

### Tensor in-built function

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### MATRIX Multiplcation

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* `(3,2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3,2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer** dimensions.
* `(2, 3) @ (3, 1)` -> `(2, 2)`

In [ ]:
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


#### Matrix Multiplacation


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
1 * 1 + 2 * 2 + 3 * 3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 1.38 ms, sys: 1.98 ms, total: 3.36 ms
Wall time: 5.42 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 511 µs, sys: 43 µs, total: 554 µs
Wall time: 399 µs


tensor(14)

### One of the most errors in deep learning is *Shape* errors.

In [ ]:
torch.matmul(torch.rand(3, 2), torch.rand(2, 3))

tensor([[0.2232, 0.4688, 0.1199],
        [0.2439, 0.4381, 0.1633],
        [0.4960, 1.0241, 0.2741]])