In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 00. PyTorch Fundamentals

In [2]:
print(torch.__version__)

2.5.1


## Introduction to Tensors
#### Creating tensors

#### Scalar

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

#### Vectors

In [7]:
vector = torch.tensor([7,7])


In [8]:
vector.ndim

1

In [9]:
vector.size()

torch.Size([2])

####  MATRIX

In [10]:
MATRIX = torch.tensor([[7,8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

## Tensor

In [14]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

In [4]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7597, 0.2848, 0.9651, 0.2255],
        [0.1568, 0.5958, 0.7984, 0.0892],
        [0.0983, 0.6300, 0.6572, 0.4809]])

In [5]:
random_tensor.ndim

2

#### Create a random tensor with similar shape to an image tensor

In [7]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels

In [9]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and ones
Create a tensor of all zeros

In [10]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

#### Create a tensor of all ones

In [13]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [14]:
ones.dtype

torch.float32

#### Creating a range of tensors and tensors-like

In [16]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
range_tersors = torch.arange(start=0, end=1000, step=77)
range_tersors

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

#### Creating tensors like

In [22]:
ten_zeros =  torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Tensor datatypes

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float32,
                               device=torch.device('cpu'),
                               requires_grad=False) # whether or not to track gradients
float_32_tensor

tensor([3., 6., 9.])

In [28]:
float_32_tensor.dtype

torch.float32

In [29]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor.dtype


torch.float16